name: ile-de-france

channels:
  - conda-forge

dependencies:
  - matplotlib=3.10.1
  - pandas=2.3.2
  - scipy=1.15.2
  - numpy=2.2.4
  - geopandas=1.1.1
  - numba=0.61.2
  - palettable=3.3.3
  - scikit-learn=1.7.2
  - shapely=2.1.1
  - tqdm=4.67.1
  - pytables=3.10.1
  - xlrd=2.0.2
  - openpyxl=3.1.5
  - pip=23.0.1
  - python=3.10.16
  - python-calamine=0.5.3
  - py7zr=0.20.8
  - pytest=8.4.2
  - xlwt=1.3.0
  - sqlite=3.49.1
  - mock=5.2.0
  - pyarrow=21.0.0
  - polars=1.33.1

  - pip:
    - synpp==1.6.1
    - bhepop2==2.0.1
    - osmium==4.1.1
