name: Tests if open data is properly accessible

on:
  schedule:
  - cron: "0 10 * * 0" # every sunday 10am

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ubuntu-latest-conda-${{ hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: "eqasim"
        environment-file: environment.yml
        python-version: "3.13"
        channels: conda-forge
        pkgs-dirs: ~/conda_pkgs_dir
        conda-remove-defaults: true
    - name: Verify availability of open data
      shell: bash -el {0}
      run: |
        python scripts/verify_data.py
